services:
  queue-setup:
    build: ./queue-setup
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    restart: "no"

  web-scraper:
    build: ./web-scraper
    depends_on:
      rabbitmq:
        condition: service_healthy
      queue-setup:
        condition: service_completed_successfully
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SCRAPE_EXCHANGE=scrape_exchange
      - SCRAPE_REQUESTS_QUEUE=scrape_requests
      - SCRAPE_RESULT_ROUTING_KEY=result
    deploy:
      replicas: 5
    restart: on-failure

  api:
    build: ./api
    depends_on:
      db:
        condition: service_started
      queue-setup:
        condition: service_completed_successfully
      elasticsearch:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://db:5432/veridion
      - DB_USER=postgres
      - DB_PASS=password
      - ELASTIC_SEARCH_URL=http://elasticsearch:9200
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_SCRAPE_EXCHANGE=scrape_exchange
      - RABBITMQ_SCRAPE_REQUEST_ROUTING_KEY=request
      - RABBITMQ_SCRAPE_RESULTS_QUEUE=scrape_results
    ports:
      - "8080:8080"

  rabbitmq:
    image: "rabbitmq:4.1-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 3s
      retries: 10

  db:
    image: "postgres:16"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: veridion
    ports:
      - "5432:5432" 

  elasticsearch:
    image: elasticsearch:9.0.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 1s
      timeout: 3s
      retries: 10
